Question 1

In [1]:
import numpy as np

In [2]:
a = np.random.rand(8)
print(a)

[0.62759148 0.35855737 0.88879057 0.1665033  0.11660222 0.56810557
 0.93145015 0.38084904]


In [3]:
def findzero(arr):
    for i in arr:
        if i == 0:
            print ("Zero found")
            return
    print("Zero not found")
    return

In [4]:
findzero(a)

Zero not found


In [5]:
a[3] = 0
findzero(a)

Zero found


Question 2

In [6]:
score = np.random.rand(15)*100
score

array([68.45777202, 43.30261073, 65.8543718 , 57.04600769, 18.99572794,
       99.15404232, 89.9612889 , 29.50548257, 67.37966445, 82.42746232,
       57.18737725, 42.95350619, 55.28074999, 11.58846079, 61.87126157])

In [7]:
def meanMeadianMarks(marks):
    #Index of students that failed
    marks = np.around(marks, 2)
    failindex = np.where(marks<=40)
    #Removing marks of the students that failed
    passed_marks = np.delete(marks, failindex)
    print(passed_marks)
    print("Median Marks :",np.around(np.median(passed_marks),2))
    print("Mean Marks:", np.around(np.mean(passed_marks),2))

In [8]:
meanMeadianMarks(score)

[68.46 43.3  65.85 57.05 99.15 89.96 67.38 82.43 57.19 42.95 55.28 61.87]
Median Marks : 63.86
Mean Marks: 65.91


Question 3

In [9]:
import numpy as np

age_labels={'18':'First','19':'Second','20':'Third','21':'Fourth'}
dob=np.array(['1999-08-15','1999-02-13','1997-08-12','2000-02-21','2000-01-14'],
             dtype='datetime64')

today=np.datetime64('2019-02-19')
difference=[]
for i in range(len(dob)):
    difference.append(str((today-dob[i])/365).replace(' days',''))
    d=np.array(difference)
print("Student's Ages",d)
for index,i in enumerate(d):
    if i in age_labels:
        print(dob[index],age_labels[i])

Student's Ages ['19' '20' '21' '19' '19']
1999-08-15 Second
1999-02-13 Third
1997-08-12 Fourth
2000-02-21 Second
2000-01-14 Second


Question 4

In [11]:
import numpy as np
arr=np.array([[5,2,29],[10,22,12],[17,8,7]])

def sorting(arr):
  sorted_arr=np.sort(arr,axis=0)
  print("2d array after sorting by column : ")
  print(sorted_arr)
  
print("2d array before sorting : ")
print(arr)
sorting(arr)

2d array before sorting : 
[[ 5  2 29]
 [10 22 12]
 [17  8  7]]
2d array after sorting by column : 
[[ 5  2  7]
 [10  8 12]
 [17 22 29]]


Question 5

In [12]:
import numpy
a=np.array([2, 3, 2, 2, 1, 4])
lis=[]
print(a)
for index,i in enumerate(a):
    b = np.zeros(4)
    b[i-1]=1
    lis.append(list(b))
print("one hot encoding is as follow")
c=np.array(lis)
print(c)

[2 3 2 2 1 4]
one hot encoding is as follow
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


Question 6

In [13]:
import numpy as np
a=np.array([4,3,5,np.nan,8,np.nan,2,0,np.nan,12,np.nan])
c=0

for i in a:
    if np.isnan(i)==True:
        a=np.delete(a,c)
    else:
        c=c+1
b=np.array(a,dtype='int')
print(b)

[ 4  3  5  8  2  0 12]


Question 7

In [14]:
import numpy as np
arr=np.array([4, 5, 3, 7, 8, 2, 6, 0, 1])
lis = []
for i in range(1,len(arr)-1):
  if(arr[i]>arr[i-1] and arr[i]>arr[i+1]):
    lis.append(i)
print("Locations of local maximas are: ")    
print (lis)

Locations of local maximas are: 
[1, 4, 6]


Question 8

In [15]:
def convert_2d(arr,w,s):
    r = arr.shape[0]
    a2d = []
    for i in range(0,r-w+1,s):
        a2d.append(arr[i:i+w])
    a2d = np.array(a2d)
    return a2d
  
arr = input("Enter array values : ").split()
arr = np.array(arr,int)
w = int(input("Enter window size : "))
s = int(input("Enter strides : "))

arr_2d = convert_2d(arr,w,s)
d2 = np.mat(arr_2d)
print("2D matrix generated is :")
print(d2)

Enter array values : 1 3 5 7 9 2 4 6 8 10 13 12 11 15
Enter window size : 4
Enter strides : 2
2D matrix generated is :
[[ 1  3  5  7]
 [ 5  7  9  2]
 [ 9  2  4  6]
 [ 4  6  8 10]
 [ 8 10 13 12]
 [13 12 11 15]]
