In [1]:
import numpy as np

**Q1. Create a function to check whether numpy array has Zero values or not.**

In [2]:
def zero_val(array):
    count = np.count_nonzero(array==0)
    if count != 0:
        print("Yes the numpy array contains zero")
    else:
        print("No the array does not have zero")


z = np.random.rand(5)
print("The random array is: ")
print(z)
zero_val(z)
print('\n')
print("Another array: ")
a = np.array([1, 2, 3, 0, 2])
print(a)
zero_val(a)

The random array is: 
[ 0.45192127  0.09021775  0.23519286  0.04574017  0.68379189]
No the array does not have zero


Another array: 
[1 2 3 0 2]
Yes the numpy array contains zero


**Q2. Consider an array contains marks of students. Find the median and mean of students who got passing marks.**


In [3]:
def get_median_mean(marks, passing_marks):
    pass_marks = marks[np.where(marks >= passing_marks)]
    print("The mean of passing students is: ")
    print(np.mean(pass_marks))
    print("\n")
    print("The median of passing students is: ")
    print(np.median(pass_marks))

z = np.random.randint(0,100,100)
print("The marks of students are: ")
print(z)
print('\n')
get_median_mean(z, 40) ## Asumming the passing marks = 40

The marks of students are: 
[65 14 14 15 14 85 91 74 41 78 41 75 21 42  8 70 91 10 56 95 24 55 65 42 57
 65  1 52 63 12 84 91 44 77 50 52 40  0 84 72 19 56 71 60 12 91 56 95 99 29
 79 15 52 14 85 17 60  5 51  6 21  4 15 86 55 51 45 22 54 24 28 24  4  7 71
 91 42 77 60 71 44 58 89 27 14 54 50 51 61 81 74 39 80 73 48 28  6 81 74 52]


The mean of passing students is: 
66.0447761194


The median of passing students is: 
65.0


**Q3. Consider an array containing date of birth of students (Use np.datetime64('2018-02-01')). Find the age of all students. If age is 18 label it First, if it is 19, label it Second, if it is 20, label it Third, if it is 21, label it Fourth.**

In [4]:
def calc_age(dob):
    present = np.datetime64('today')
    days_in_yr = 365.2425
    days = np.int64(present - dob) 
    yrs =  np.int64(days // days_in_yr)
    return max(0, yrs-17)

def get_label(dates):
    labels = np.array([calc_age(x) for x in dates])
    labels_dict = {1: 'First', 2: 'Second', 3: 'Third', 4: 'Fourth'}
    return [labels_dict[x] for x in labels]

dates = np.array(['2000-01-13', '1998-06-15', '1997-08-13'], dtype='datetime64')
labels = get_label(dates)
print(labels)

['Second', 'Third', 'Fourth']


**Q4. Create a function to sort 2d Array by a column.**

In [5]:
def sort_array_by_column(array):
    array = array[array[:,0].argsort()]
    return array

z = np.array([[1,2,3],[4,5,6],[8,0,1]])
print("The array is: ")
print(z)
print('\n')
print("After sorting the matrix is: ")
sort_arr = sort_array_by_column(z)
print(sort_arr)

The array is: 
[[1 2 3]
 [4 5 6]
 [8 0 1]]


After sorting the matrix is: 
[[1 2 3]
 [4 5 6]
 [8 0 1]]


**Q5. Create one hot encoding of an array. For example For an** `array([2, 3, 2, 2, 2, 1])` **Output should be**

   ```
   array([[ 0.,  1.,  0.],

             [ 0.,  0.,  1.],

             [ 0.,  1.,  0.],

             [ 0.,  1.,  0.],

             [ 0.,  1.,  0.],

            [ 1.,  0.,  0.]])
    ```

In [6]:
import numpy as np
nb_classes = 3
targets = np.array([[2, 3, 2, 2, 2, 1]]).reshape(-1)
targets = targets - 1
one_hot_targets = np.eye(nb_classes)[targets]
print(one_hot_targets)

[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]]


**Q6. Drop all missing values from an array Input: np.array([1,2,3,np.nan,5,6,7,np.nan]) Desired Output: array([ 1.,2.,3.,5.,6.,7.])**

In [7]:
x = np.array([1,2,3,np.nan,5,6,7,np.nan])
print("The entered array is: ")
print(x)
print('\n')
x = x[~np.isnan(x)]
print("After removing the missing values the array is: ")
print(x)

The entered array is: 
[  1.   2.   3.  nan   5.   6.   7.  nan]


After removing the missing values the array is: 
[ 1.  2.  3.  5.  6.  7.]


**Q7. Find Local maxima from an array. Input: a = np.array([1, 3, 7, 1, 2, 6, 0, 1]) Desired Output: array([2, 5, 7])**

In [8]:
def get_max(arr):
    indices = np.arange(0, len(arr)-1, 1)
    local_maximas = []
    
    if arr[0] > arr[1]:
        local_maximas.append(0)
    
    for x in indices:
        if x != 0:
            if arr[x] > arr[x-1] and arr[x] > arr[x+1]:
                local_maximas.append(x)
    
    if arr[-1] > arr[-2]:
        local_maximas.append(len(arr)-1)
    
    return np.array(local_maximas)

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
print(get_max(a))

[2 5 7]


**Q8.From the given 1d array arr, generate a 2d matrix using strides, For example for an** `array ([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])` **with a window length of** `w=4` **and strides of** `s=2`, **like** `[[0,1,2,3], [2,3,4,5], [4,5,6,7]..]` **w and s will be provided by user**

In [9]:
def get_conv(arr, w, s):
    indices = np.arange(0, len(arr), s)
    mat = []
    for i in indices:
        if i + w < len(arr):
            mat.append(arr[i:i+w])
        else:
            temp = arr[i:]
            diff = w - len(temp)
            temp = np.concatenate((temp, np.zeros(diff, np.int64)), axis=0)
            mat.append(temp)
    return np.array(mat)

a = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
print(get_conv(a, 4, 2))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]
 [12 13 14  0]
 [14  0  0  0]]
